sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t paulyuan1219/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true paulyuan1219/docker-react npm run test